name: Publish a new docker image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build and publish image
        run: |
          docker login --username rankguessr --password ${{ secrets.GH_PAT }} ghcr.io
          docker build -t ghcr.io/rankguessr/web:${{ github.ref_name }} -t ghcr.io/rankguessr/web:latest .
          docker push ghcr.io/rankguessr/web:${{ github.ref_name }}
          docker push ghcr.io/rankguessr/web:latest
